export const PRICING_TIERS = {
  hobby: {
    name: "Hobby",
    price: "$9.99",
    priceValue: 9.99,
    period: "/month",
    description: "Perfect for trying out StoryForge",
    features: [
      "3 projects maximum",
      "25,000 tokens per month",
      "20,000 words per month",
      "TXT export only",
      "10-second generation cooldown",
      "Community support",
    ],
    cta: "Start Writing",
    href: "/auth/signin",
    popular: false,
    highlight: false,
    backendTier: "hobby" as const,
  },
  professional: {
    name: "Professional",
    price: "$49.99",
    priceValue: 49.99,
    period: "/month",
    description: "For serious writers",
    features: [
      "Unlimited projects",
      "150,000 tokens per month",
      "120,000 words per month",
      "TXT + PDF export",
      "3-second generation cooldown",
      "Priority support",
    ],
    cta: "Start Free Trial",
    href: "/auth/signin",
    popular: true,
    highlight: true,
    backendTier: "professional" as const,
  },
  enterprise: {
    name: "Enterprise",
    price: "$149.99",
    priceValue: 149.99,
    period: "/month",
    description: "For professional authors",
    features: [
      "Unlimited projects",
      "500,000 tokens per month",
      "400,000 words per month",
      "TXT + PDF + EPUB export",
      "1-second generation cooldown",
      "Dedicated support",
    ],
    cta: "Contact Sales",
    href: "/auth/signin",
    popular: false,
    highlight: false,
    backendTier: "enterprise" as const,
  },
} as const;

export type TierKey = keyof typeof PRICING_TIERS;
